lang: fr
title: "Sécheresses : ne pas être pris par surprise"
description: "À quel point allons-nous manquer d'eau en France ?"
logo: /assets/img/logo.png
image: /assets/img/capture-printemps-2050.png
twitter:
  card: summary_large_image

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true
